webapp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired




class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

webapp/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort,Blueprint
from webapp.posts.forms import PostForm
from webapp.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from webapp import db
from webapp.db_models import Post
from flask_login import current_user,login_required




posts = Blueprint('posts', __name__)







@posts.route("/post/new", methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash(f"Post has been created!", 'success')
        return redirect(url_for('main.home'))

    return render_template('create_post.html', form=form)

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', post=post, legend='New Post')


@posts.route("/post/<int:post_id>/update", methods=["GET", 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        flash(f"Updating post!", 'success')
        db.session.commit()
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content


    return render_template('create_post.html', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash(f"Post has been deleted.", 'success')
    return redirect(url_for('main.home'))

webapp/users/routes.py
from flask import render_template, url_for, flash,redirect, request,Blueprint
from webapp.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from webapp.users.utils import save_picture
from webapp import db, bcrypt
from webapp.db_models import Post, User
from flask_login import login_user, current_user, logout_user, login_required

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash(f"You are already logged in", 'success')
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,email=form.email.data, password=hashed_pass)
        db.session.add(user)
        db.session.commit()
        flash(f"Welcome {form.username.data} your account has been created!", 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash(f"You are already logged in", 'success')
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user_pass_input = form.password.data
        user = User.query.filter_by(email=form.email.data).first()


        if user and bcrypt.check_password_hash(user.password, user_pass_input):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f"Hey you have been logged in!", 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash("WRONG email or password", 'danger')
    return render_template('login.html', form=form)




@users.route("/logout")
def logout():
    flash(f"You have been logged out", 'success')
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash(f"We updated your account info!", 'success')
        return redirect(url_for('users.account'))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='images/' + current_user.image_file)
    return render_template('account.html', image_file=image_file, form=form)



@users.route("/user/<string:username>")
def user_post(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)

    return render_template('user_post.html', posts=posts, user=user)

webapp/templates/about.html
{% extends 'base.html' %}
{% block head %}
<title>About</title>
{% endblock %}


{% block content %}
<h1>flask print('hello')</h1>

{% endblock %}

webapp/templates/account.html
{% extends 'base.html' %}
{% block head %}
<title>Account</title>
{% endblock %}


{% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <!-- FORM HERE -->


    <div class="content-section">
        <form method="Post" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update Account Info</legend>
                <div class="form-group">

                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class='form-control-file') }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}

                    {% endif %}

                </div>

            </fieldset>
            <div class="form-group mt-2 mb-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>


</div>

{% endblock %}

webapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  {% block head %}{% endblock %}
  </head>
  <body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="/">Home</a>
            <a class="nav-item nav-link" href="/about">About</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">

            {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="/post/new">Create Post</a>
              <a class="nav-item nav-link" href="/account">Account</a>
              <a class="nav-item nav-link" href="/logout">Log out</a>


            {% else %}
              <a class="nav-item nav-link" href="/login">Login</a>
              <a class="nav-item nav-link" href="/register">Register</a>
            {% endif %}

          </div>
        </div>
      </div>
    </nav>
  </header>

<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {%for cat, message in messages %}
      <div class="alert alert-{{ cat }}">{{ message }}</div>
      {% endfor %}
      {% endif %}
      {% endwith %}
      {% block content %}

      {% endblock %}
    </div>
    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/create_post.html
{% extends 'base.html' %}
{% block head %}
<title>Create_post</title>
{% endblock %}


{% block content %}
<div class="content-section">
    <form method="Post" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">

                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>


        </fieldset>
        <div class="form-group mt-2 mb-2">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>

        <div class="border-top pt-3">
        </div>

    </form>

</div>

{% endblock %}

webapp/templates/index.html
{% extends 'base.html' %}


{% block head %}
<title>Home</title>

{% endblock %}


{% block content %}
    {% for post in posts.items %}

    <article class="media content-section">
        <img src="{{ url_for('static', filename='images/' + post.author.image_file) }}" class="rounded-circle article-img">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>

          <small class="text-muted">{{ post.date_posted.strftime("%d/%m/%Y") }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>

      </div>
    </article>

 {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=2, right_edge=2, left_current=1, right_current=2) %}
    {% if page_num %}
    {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
    {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>

    {% endif %}
    {% else %}
        ...
    {% endif %}
    {% endfor %}


{% endblock %}

webapp/templates/login.html
{% extends 'base.html' %}


{% block head %}
<title>Login</title>
{% endblock %}


{% block content %}
<div class = "content-section">
    <form method="Post" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="form-group">

                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>

        </fieldset>
        <div class="form-group mt-2 mb-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>

        <div class="border-top pt-3" >
            <small class="text-muted">
                <a class="ml-2 " href="{{ url_for('users.login') }}">Forgot password?</a>
            </small>
            <small class="text-muted">
                Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Create account</a>
            </small>
        </div>

    </form>

</div>



{% endblock %}

webapp/templates/post.html
{% extends 'base.html' %}


{% block head %}
<title>Post</title>

{% endblock %}


{% block content %}
<article class="media content-section">
    <img src="{{ url_for('static', filename='images/' + post.author.image_file) }}" class="rounded-circle article-img">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>

            <small class="text-muted">{{ post.date_posted.strftime("%d/%m/%Y") }}</small>
            {% if post.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>

            </div>
            {% endif %}


        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>

    </div>

</article>
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>


{% endblock %}

webapp/templates/register.html
{% extends 'base.html' %}


{% block head %}
<title>Register</title>
{% endblock %}


{% block content %}
<div class="content-section">
    <form method="Post" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="form-group">

                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}


            </div>
            <div class="form-group">


                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}


            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>

        </fieldset>
        <div class="form-group mt-2 mb-2">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>

    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign in </a>
        </small>
    </div>


    {% endblock %}
</div>

webapp/templates/user_post.html
{% extends 'base.html' %}


{% block head %}
<title>{{ user.username}}'s Posts</title>

{% endblock %}


{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}

    <article class="media content-section">
        <img src="{{ url_for('static', filename='images/' + post.author.image_file) }}" class="rounded-circle article-img">
      <div class="media-body">
        <div class="article-metadata">

          <a class="mr-2" href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>

          <small class="text-muted">{{ post.date_posted.strftime("%d/%m/%Y") }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>

      </div>
    </article>

 {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=2, right_edge=2, left_current=1, right_current=2) %}
    {% if page_num %}
    {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('users.user_post',username=user.username, page=page_num) }}">{{ page_num }}</a>
    {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_post',username=user.username, page=page_num) }}">{{ page_num }}</a>

    {% endif %}
    {% else %}
        ...
    {% endif %}
    {% endfor %}


{% endblock %}